# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

repository: sunghee-yun/sunghee-yun.github.io

title: Convex Optimization Homepage
email: sunghee.yun@gmail.com
description: This is the space to discuss virtually every aspect of Convex Optimization.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
#theme: minimal-mistakes-jekyll
minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: US/Pacific # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name             : "Convex Optimization"
  avatar           : "/assets/images/twisted-volumes.png"
  bio              : "Dual Problems"
  location         : "Silicon Valley, CA, USA"
  email            : convex.optimization.99@gmail.com
  links:
    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/convex-optimization-99/convex-optimization-99.github.io"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/sungheeyun/"
    - label: "Blog"
      icon: "fa-solid fa-blog"
      url: "https://sungheeyun.github.io"
    - label: "Mathematics Genealogy Project"
      icon: "fa-solid fa-infinity"
      url: "https://www.genealogy.math.ndsu.nodak.edu/id.php?id=283283"
    - label: "Erudio Bio, Inc."
      icon: "fa-solid fa-dna"
      url: "https://sungheeyun-erudio.github.io"
    - label: "K-PAI"
      icon: "fa-solid fa-chart-pie"
      url: "https://k-privateai.github.io/"
    - label: "Salzburg Global Leadership Initiative"
      icon: "fa-solid fa-globe"
      url: "https://www.salzburgglobal.org/multi-year-series/kfas/pageId/11076"
    - label: "Solar"
      icon: "fa-solid fa-sun"
      url: "https://solar-society.github.io"
#    - label: "Email"
#      icon: "fa-solid fa-envelope"
#      url: "mailto:sunghee.yun@gmail.com"
    - label: "CV"
      icon: "fa-solid fa-file"
      url: "/resource/CV/Sunghee_Yun_CV_2.pdf"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/sunghee-yun/sunghee-yun.github.io"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/sungheeyun/"
    - label: "Blog"
      icon: "fa-solid fa-blog"
      url: "https://sungheeyun.github.io"
    - label: "Mathematics Genealogy Project"
      icon: "fa-solid fa-infinity"
      url: "https://www.genealogy.math.ndsu.nodak.edu/id.php?id=283283"
    - label: "Erudio Bio, Inc."
      icon: "fa-solid fa-dna"
      url: "https://sungheeyun-erudio.github.io"
    - label: "K-PAI"
      icon: "fa-solid fa-chart-pie"
      url: "https://k-privateai.github.io/"
    - label: "Salzburg Global Leadership Initiative"
      icon: "fa-solid fa-globe"
      url: "https://www.salzburgglobal.org/multi-year-series/kfas/pageId/11076"
    - label: "Solar"
      icon: "fa-solid fa-sun"
      url: "https://solar-society.github.io"
#    - label: "Email"
#      icon: "fa-solid fa-envelope"
#      url: "mailto:sunghee.yun@gmail.com"
    - label: "CV"
      icon: "fa-solid fa-file"
      url: "/resource/CV/Sunghee_Yun_CV_2.pdf"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      #classes: wide
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      #classes: wide
      layout: single
      author_profile: true

category:
  type: liquid
  path: /categories/
tag:
  type: liquid
  path: /tags/
